"""replies

Revision ID: 40bc1ab2517f
Revises: 
Create Date: 2023-03-04 13:15:08.074839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bc1ab2517f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('replyto', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(length=1000), nullable=True),
    sa.Column('replier', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['replier'], ['users.id'], name=op.f('fk_replies_replier_users')),
    sa.ForeignKeyConstraint(['replyto'], ['posts.id'], name=op.f('fk_replies_replyto_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replies'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=255), nullable=True))

    op.drop_table('replies')
    # ### end Alembic commands ###
